---
- hosts: appserver 
  vars:
    kernel_ver: 4.15.1
  tasks:
  - name: install development tools package group
    yum: name="@Development tools" state=present update_cache=yes

  - name: install kernel dev packages
    yum: name={{ item }} state=present
    with_items: 
    - ncurses-devel
    - bc
    - gcc*
    - openssl-devel
    - hmaccalc
    - zlib-devel
    - binutils-devel
    - elfutils-libelf-devel

  - name: download kernel
    get_url:
      url: https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.15.1.tar.xz
      dest: /tmp/linux-{{ kernel_ver }}.tar.xz

  - name: untar kernel
    shell: tar -Jxvf linux-{{ kernel_ver }}.tar.xz
    args:
      chdir: /tmp/


  - name: install kernel
    shell: "{{ item }}"
    with_items:
    - make defconfig
    - make 
    - make modules
    - make modules_install
    - make install
    args:
      chdir: /tmp/linux-{{ kernel_ver }}/

  - name: restart machine
    shell: sleep 2 && shutdown -r +1 "Ansible updates triggered"
    async: 1
    poll: 0
    sudo: true
    ignore_errors: true

  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
    sudo: false

  - name: rerun make install to correct grub entry order
    shell: make install 
    args:
      chdir: /tmp/linux-{{ kernel_ver }}/

  - name: restart machine
    shell: sleep 2 && shutdown -r +1 "Ansible updates triggered"
    async: 1
    poll: 0
    sudo: true
    ignore_errors: true

  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
    sudo: false
 
  - name: confirm kernel version
    shell: uname -a
    register: kernel_version

  - debug: var=kernel_version.stdout
