galaxy_info:
  author: Serge Kamgang
  description: Install LAMP stack
  license: BSD
  min_ansible_version: 2.2
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - web
    - database:
